apiVersion: apps/v1
kind: Deployment
metadata:
  name: delux-app-deployment
  labels:
    app: delux-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delux-app
  template:
    metadata:
      labels:
        app: delux-app
    spec:
      imagePullSecrets:
      - name: my-key
      containers:
      - name: delux-app
        image: 597086837351.dkr.ecr.us-east-2.amazonaws.com/delux_private:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
